# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 645aa661dc8da245848ade6cb7fba5458831dcf18aabe71b3325cc229aade17d00ad1daec182101120c6de9731e3da306d12de2121676896901eec57b75cca10

test:
  secret_key_base: 1e72fdace7eb4d725dc9d5e13f3962efc98db56ddad3ab19ce143a05cdc9a253fc60b378c4bd0bc6e964235b38af99bb21e79a66653afe1b4af6938eaee89423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
